trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: firstjob
    steps: 
    - bash: echo first job
  - job: secondjob
    steps: 
    - bash: echo second job 
- stage: DevDeploy
  dependsOn: Build
  jobs:
  - job: firstjob
    steps: 
    - bash: echo first job
  - job: secondjob
    steps: 
    - bash: echo second job 
- stage: QADeploy
  dependsOn: Build
  jobs:
  - job: firstjob
    steps: 
    - bash: echo first job
  - job: secondjob
    steps: 
    - bash: echo second job 
- stage: ProdBuild
  dependsOn: 
  - DevDeploy
  - QADeploy
  jobs:
  - job: firstjob
    steps: 
    - bash: echo first job
  - job: secondjob
    steps: 
    - bash: echo second job 
 

  